// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderTest.Repositories.Context;

namespace OrderTest.Repositories.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200228131804_init3")]
    partial class init3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderTest.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58899e6d-14e2-4326-9af3-481ed55d44a1"),
                            CreationDate = new DateTime(2020, 2, 28, 13, 18, 3, 965, DateTimeKind.Utc).AddTicks(794),
                            Name = "Order 1",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d38d853d-03fc-4512-8ac9-d84f3c84233f"),
                            CreationDate = new DateTime(2020, 2, 28, 13, 18, 3, 965, DateTimeKind.Utc).AddTicks(3778),
                            Name = "Order 2",
                            Status = 1
                        });
                });

            modelBuilder.Entity("OrderTest.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9141d1d1-62c8-41ba-9519-77d6ff9c7169"),
                            Name = "Prod 1",
                            OrderId = new Guid("58899e6d-14e2-4326-9af3-481ed55d44a1"),
                            Price = 10m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("3c5a4cb0-f109-4c84-8533-ebe158d3c6aa"),
                            Name = "Prod 2",
                            OrderId = new Guid("58899e6d-14e2-4326-9af3-481ed55d44a1"),
                            Price = 1m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("d07822a5-5745-42a7-97de-f7d790e0e2c7"),
                            Name = "Prod 3",
                            OrderId = new Guid("58899e6d-14e2-4326-9af3-481ed55d44a1"),
                            Price = 65m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("d6d0fa4e-f6a0-418d-9a5d-2f0b8d580979"),
                            Name = "Prod 4",
                            OrderId = new Guid("58899e6d-14e2-4326-9af3-481ed55d44a1"),
                            Price = 100m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("b8c9e71b-76e5-40e7-90c3-87c06a7d2c55"),
                            Name = "Prod 5",
                            OrderId = new Guid("d38d853d-03fc-4512-8ac9-d84f3c84233f"),
                            Price = 10m,
                            Quantity = 150
                        });
                });

            modelBuilder.Entity("OrderTest.Entities.Product", b =>
                {
                    b.HasOne("OrderTest.Entities.Order", "Order")
                        .WithMany("ProductsList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
